production:
  adapter: redis
  #este é onde está o produto final
  url: redis://redistogo:9e1ebefbb768b188ce000f759a2ab2b2@sculpin.redistogo.com:9614/
  
  

development:
  adapter: async
  url: redis://localhost:6379
test:
  adapter: async
